trigger:
  branches:
    include:
      - main

variables:
  tag: '$(Build.BuildId)'
  azureContainerRegistry: '<your-acr-name>.azurecr.io'

stages:
  - stage: Build
    displayName: Build and Push Docker Images
    jobs:
      - job: BuildAndPush
        displayName: Docker Build and Push
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: DockerInstaller@0
            displayName: Install Docker

          - task: Docker@2
            displayName: Build and push Vote image
            inputs:
              containerRegistry: '$(azureContainerRegistry)'
              repository: 'vote'
              command: 'buildAndPush'
              Dockerfile: 'dockerfiles/vote.Dockerfile'
              tags: |
                $(tag)

          - task: Docker@2
            displayName: Build and push Result image
            inputs:
              containerRegistry: '$(azureContainerRegistry)'
              repository: 'result'
              command: 'buildAndPush'
              Dockerfile: 'dockerfiles/result.Dockerfile'
              tags: |
                $(tag)

