trigger:
  branches:
    include:
      - main

variables:
  tag: '$(Build.BuildId)'

stages:
  - stage: Build
    displayName: Build Docker Images (No Push Yet)
    jobs:
      - job: BuildOnly
        displayName: Docker Build Only
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: DockerInstaller@0
            displayName: Install Docker

          - script: docker build -t vote:$(tag) -f dockerfiles/vote.Dockerfile .
            displayName: Build Vote image

          - script: docker build -t result:$(tag) -f dockerfiles/result.Dockerfile .
            displayName: Build Result image
