apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: worker-service-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: worker
  endpoints:
  - port: http-metrics
    path: /metrics
    interval: 30s

