# --- VOTE APP DEPLOYMENT (Frontend) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: acrvotingappterraformnew.azurecr.io/voteapp:97
        name: vote
        ports:
        - containerPort: 80
          name: vote
      imagePullSecrets:
      - name: acr-secret

# --- VOTE APP SERVICE (LoadBalancer) ---
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote-service
spec:
  type: LoadBalancer
  ports:
  - name: "vote-service"
    port: 8080
    targetPort: 80
    nodePort: 32133
  selector:
    app: vote
